[package]
name = "rain"
version = "0.1.0"
edition = "2021"
authors = ["Korbinian Schreiber"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# num = "0.4.0"
rodio = "0.14.0"